### ISSUE TITLE
Support for Unicode in the running text

### ISSUE THREAD

**Issue by yaronf** [cabo/kramdown-rfc2629#105]
I'm trying to include Unicode text, a.k.a. people's names, in the Acknowledgement section. Is there syntax for it?

(An hour later, found the answer, could you please document it?)

``
<contact fullname="Frédéric" asciiFullname="Frederic"/> Fieau
``

**Comment by cabo** [comment]
Yeah, pretty well hidden in <https://mailarchive.ietf.org/arch/msg/rfc-markdown/7spMIPZdz6S8_NbZZ2WcSB-ScPY>

Now at https://github.com/cabo/kramdown-rfc2629/wiki/Syntax#-syntax-2

**Comment by yaronf** [comment]
Thanks!

**Comment by reschke** [comment]
~~~
<contact fullname="Frédéric" asciiFullname="Frederic"/> Fieau
~~~

FTR, that's really a poor way to mark things up. Better would be:

~~~
<contact fullname="Frédéric Fieau" asciiFullname="Frederic Fieau"/> 
~~~

Also, if the non-ASCII characters are just Latin-1 chars, the ASCII alternative shouldn't be needed at all.

**Comment by cabo** [comment]
> Also, if the non-ASCII characters are just Latin-1 chars, the ASCII alternative shouldn't be needed at all.

To your second point: when I try that, kramdown-rfc2629 removes the diacritics, resulting in a plain "Frederic".

It's not kramdown-rfc2629 that converts beyond-ASCII into a surrogate (the Frédéric is in the XML it puts out), it's xml2rfc.  Specifically, for a v2 input document (which is what kramdown-rfc generates today), the v2v3 conversion uses the old xml2rfc surrogates.  If kramdown-rfc were to output a v3 document, you'd get the more beautiful Fr&#233;d&#233;ric Fieau.

There is no way around the `contact` hack at the moment.
Of course, kramdown-rfc could insert contact elements automatically, but I'm not sure people would like that (and it would then definitely only mark up Frédéric).
The fact that xml2rfc's RNC grammar is broken (contact is allowed in section and t, but not in, say, li) does not help either.

**Comment by cabo** [comment]
Note that the above needed to be edited to show the wonderful `Fr&#233;d&#233;ric`(edited: github "fixes" that for me!).
