### ISSUE TITLE
Is {::include supposed to work in included files?

### ISSUE THREAD

**Issue by dkg** [cabo/kramdown-rfc2629#106]
I have a draft that is using `{::include` to include another markdown file, and that secondary file itself has `{::include` in it, referring to some generated artifacts.

Only the first layer of `{::include`s seems to work. The ones on the second level are rendered verbatim, instead of including the generated artifacts.

Is this intentional?  I recognize that permitting nested `{::include`s could lead to infinite recursion, which would be a Bad Thing™.

**Comment by cabo** [comment]
It's not intentional in the sense that we never want that to happen, it's just a non-feature.

I think that we would want to add a flag to make this happen, e.g.

```
{::include-recursive foo.md}
```
To switch on one level of recursion (foo.md could do an `include-recursive` to enable the next level etc.).

**Comment by CxRes** [comment]
Can you please document this feature? I cannot seem to get it work.

I have tried using `include-recusive` and `include-nested`!

**Comment by cabo** [comment]
Do you have an example where `included-nested` didn't work?

**Comment by CxRes** [comment]
On my PC only atm! I am working on converting a W3C spec to an I-D and hitting various issues. This seemed to be the lowest hanging fruit to ask about first.

Is there a sandbox where I can create a repro or do I have to clone i-d-template and create an example there?

**Comment by cabo** [comment]
You could attach the including and the included file to this issue

**Comment by CxRes** [comment]
Here is an extracted example from my I-D...

Main File:
[draft-gupta-httpbis-per-resource-events-test.md](https://github.com/cabo/kramdown-rfc/files/12570989/draft-gupta-httpbis-per-resource-events-test.md)

Included File:
[discovery-test.md](https://github.com/cabo/kramdown-rfc/files/12571003/discovery-test.md)

Sub Included Files
cat test.md > #Foo
cat request.http.txt > Some HTTP Code

Command
```
$ kramdown-rfc2629 -3 draft-gupta-httpbis-per-resource-events-test.md > draft-gupta-httpbis-per-resource-events-test.xml
---
- 'No or invalid attributes found in IAL/ALD content: test.md'
- No stop tag for extension 'include' found on line 83 - ignoring it
- Found span IAL after text - ignoring it
- 'No or invalid attributes found in IAL/ALD content: src/sections/request.http.txt'
- No stop tag for extension 'include' found on line 89 - ignoring it

$kramdown-rfc --version
kramdown-rfc 1.6.39
```

**Comment by CxRes** [comment]
My output (renamed to txt because of Github upload rules):
[draft-gupta-httpbis-per-resource-events-test.xml.txt](https://github.com/cabo/kramdown-rfc/files/12571018/draft-gupta-httpbis-per-resource-events-test.xml.txt)

**Comment by cabo** [comment]
Interesting. 

You need to have a blank line before the code block, but that should not stop -nested from working. 

Since I'm on vacation and have little IT with me: 
Can you try the original 1.5.23?

Gem install that via -v1.5.23, and call kramdown-rfc with _1.5.23_ as the first argument.

**Comment by CxRes** [comment]
Are you sure there is a 1.5.23? 

I got this error:
ERROR:  Could not find a valid gem 'kramdown-rfc' (= 1.5.23) in any repository
ERROR:  Possible alternatives: kramdown-rfc

Then I checked rubygems which lists only versions after 1.6.1:
<https://rubygems.org/gems/kramdown-rfc/versions>

**Comment by CxRes** [comment]
I managed to download kramdown-rfc2629 1.5.24 (there is no 1.5.23) in the gems database. I can run it but without `-3` flag which still gives me the same output as before. I am unable to run `-3` flag which just is ignored.

**Comment by cabo** [comment]
I probably never tested this with crlf (windows) files. Can you try a dos 2 Unix or equivalent?

**Comment by CxRes** [comment]
CRLF is not the issue. I converted all the files to LF and ran both versions. No change!

**Comment by cabo** [comment]
Sorry for the goose chase. So it seems this will have to wait for me being back from vacation on Sunday. Apologies for the wait.

**Comment by CxRes** [comment]
No worries! Thanks for responding so promptly!!! :)

I will have other issues for you also by then...

**Comment by CxRes** [comment]
I managed to lay hands (temporarily) on another PC with WSL/Ubuntu 22 LTS. I can confirm this is indeed a Windows problem. My suspicion is that it might have something to do with path normalization (though I don't speak ruby).

In any case, it would be helpful if all the flags of `::include` were fully documented.

**Comment by rfc2822** [comment]
Had the same problem. Works when using `::include-nested` on top level.
