### ISSUE TITLE
<refcontent> elements in references

### ISSUE THREAD

**Issue by martinthomson** [cabo/kramdown-rfc2629#111]
The RPC have added a bunch of `<refcontent>` elements to references in a document I'm working on.  Can kramdown be taught to pass these along if provided?

Opening this to track it, I'm willing to attempt writing a change if the feature request is acceptable.

**Comment by cabo** [comment]
Added in 1.4.4.
Note that multiple refcontent elements are joined by spaces at the moment; this may violate some aesthetics.
I put in the abbreviation "rc", which I'm about as happy with as with "refcontent" in the first place...

**Comment by martinthomson** [comment]
Thanks Carsten!  I can confirm that it works perfectly.

(I share your reservations about \<refcontent\>, but I'm working through AUTH48 and I have no interest in fixing all of the problems at once.)
