### ISSUE TITLE
<bcp14> tags

### ISSUE THREAD

**Issue by martinthomson** [cabo/kramdown-rfc2629#114]
I think that it would be relatively easy to add these automatically if you wanted.  I don't like them much myself, but the RFC editor insists on adding them and it makes AUTH48 easier if your XML doesn't have lots of trivial edits like that.

**Comment by cabo** [comment]
I was toying with the idea of letting kramdown do most of the work; either directly using abbreviations [^1] or stealing that code (lib/kramdown/parser/kramdown/abbreviation.rb).

Could enable that out of `{::boilerplate bcp14}` or a variant of that.

[^1]: https://kramdown.gettalong.org/syntax.html#abbreviations

**Comment by cabo** [comment]
Enable via:

```
{::boilerplate bcp14-tagged}
```

(requires --v3).
