### ISSUE TITLE
Singular <t> elements under <li>, <dd>, and friends

### ISSUE THREAD

**Issue by martinthomson** [cabo/kramdown-rfc2629#115]
A recent document that went through AUTH48 originally had a single \<t> element as a child of a \<dd> element.  The RFC editor decided that this wasn't nice and removed the \<t>.  I couldn't work out how to massage the input to effect the same change, but maybe a little streamlining is possible from this end.

Right now, I've told the RFC editor that I won't accept the change.  Write XML tags directly is best avoided and the extra tags aren't doing any harm.  You might argue even that consistency argues for them staying.  But if the optimization were automated, that could be different.

**Comment by cabo** [comment]
The current `convert_dd` lets the xml2rfc v2v3 conversion handle the complexity.
Of course, it could check whether grammar alternative 1 holds and leave out the `<t>`.
But I don't really know why.

**Comment by martinthomson** [comment]
I'm going to close this one; I think that your response is entirely appropriate (it was the same as my own).
