### ISSUE TITLE
xref text content

### ISSUE THREAD

**Issue by martinthomson** [cabo/kramdown-rfc2629#116]
The RFC editor has proposed the following form of reference:

```xml
Section <xref target="RFC9001" section="5.8" sectionFormat="bare">"Retry Packet Integrity"</xref> of <xref target="RFC9001"/>
```

This renders as `Section |5.8| (|"Retry Packet Integrity"|) of [|RFC9001|]` with "|" showing where links appear.

Is there any reason I shouldn't propose a change that allows `{{.*>text}}` to render with *text* as the textContent of the `<xref>` element?

It seems to me like this would apply to all forms of reference.

**Comment by cabo** [comment]
Not sure I understand the `{{.*>text}}` part.

Wouldn't the natural reference format be:

```
{{Section 5.8 ("Retry Packet Integrity") of RFC9001}}
```

(not sure about the quotes)

In the long run, of course I'd like kramdown-rfc to dig out that section title for you.

```
{{Section 5.8 () of RFC9001}}
```

**Comment by cabo** [comment]
The RE (with all the Appendices goo as well) is going to get humungous.  It probably needs to be computed.
(And it will need to match Parentheses inside the text.)
Sounds like a fun weekend project :-)

Of course, we already have ["Retry Packet Integrity"](#RFC9001){: section="5.8" sectionFormat="bare"} as the "standard" markdown way of writing the above.
