### ISSUE TITLE
YAML contributor not working

### ISSUE THREAD

**Issue by italobusi** [cabo/kramdown-rfc2629#119]
The following YAML contributor syntax is causing errors with kramdown-rfc2629:

```
contributor:
-
    name: Contributor1
-
    name: Contributor2
```

The error message says:

> *** Cannot process YAML contributors under V2 rules
> *** attributes left {"contributor"=>[{"name"=>"Contributor1"}, {"name"=>"Contributor2"}]}!

[test.md](https://github.com/cabo/kramdown-rfc2629/files/6406897/test.md)

This error appears both with my local installation as well as with the on-line tool:

https://xml2rfc.tools.ietf.org/experimental.html

**Comment by cabo** [comment]
Yes, you need to switch on RFCXMLv3 processing by using

`kdrfc -3`

(or `kramdown-rfc2629 --v3` if you are calling that directly).
