### ISSUE TITLE
Smart quotes in references

### ISSUE THREAD

**Issue by martinthomson** [cabo/kramdown-rfc2629#123]
The RFC editor picked up on this, and I thought it worth passing along.

QUIC cited a paper from "CCS '18".  Note the single quote.  That string was provided in a reference block in YAML (using refcontent, though that hardly matters for this).  The RFC editor were not happy with that being turned into U+2018.

For those who encounter this problem, you need TWO backslashes (i.e., "CCS \\'18") to suppress the conversion.  YAML takes one, kramdown takes the other.

**Comment by cabo** [comment]
The --v3 setting switch off smart quotes, so I'm confused about what actually happened.

**Comment by cabo** [comment]
Ah, of course, it is the embedded markdown processing.  $global_markdown_options doesn't carry that information through yet.

**Comment by cabo** [comment]
Yep, happens in xref text, too.

**Comment by cabo** [comment]
Because finally fixing these bugs needed some more refactoring than I usually do, I pushed a 1.4.14.pre (prerelease).
Please install with 

```
gem update kramdown-rfc2629 --pre
```

Feedback welcome.

**Comment by martinthomson** [comment]
This seems to work.  I need to remove my workaround or I get backslashes in references, but that's manageable.  Thanks for doing this.
