### ISSUE TITLE
goat alternative: aasvg

### ISSUE THREAD

**Issue by martinthomson** [cabo/kramdown-rfc2629#133]
After discovering that goat was doing ... things to diagrams, @reschke produced an XSLT program that fixes up diagrams.  This is fine, but it seemed better to go for the source.

[goat](https://github.com/blampe/goat) seems to have been mostly abandoned, but the code that it ports - [markdeep](https://casual-effects.com/markdeep/) - is not.  Markdeep does a bunch more than what we're looking to use, so I extracted the relevant pieces and fixed them up: [aasvg](https://github.com/martinthomson/aasvg).

Functionally, this is equivalent to goat.  However, it is easier to ensure that it is available.  How would you prefer to manage the two?  Do you think it best to use the "goat" tag (and "protocol-goat") and just pick a preferred tool to invoke, with a fallback to the other?  If that is the case, should an alias "aasvg" tag be recognized?  Or do you think it best to have entirely separate tags?

**Comment by cabo** [comment]
So far, we have used the actual tool names in the language field (except for "math", which maybe should have an alias with the tool names, too).  So I'd lean towards replicating the goat and protocol-goat language field values as aasvg and protocol-aasvg to stay consistent.  Mutual fallback might be useful, but I would expect we won't have feature parity for that long...

**Comment by martinthomson** [comment]
Fixed in #134; I just forgot to include "Closes #x".
