### ISSUE TITLE
Include datatracker link in discussion venues

### ISSUE THREAD

**Issue by mnot** [cabo/kramdown-rfc2629#141]
... seems like a good idea.

**Comment by cabo** [comment]
Hmm, how would I get that -- add another key to the venue block with the actual draft name?
Sounds a bit redundant with the docname, which however includes -latest...

**Comment by mnot** [comment]
I think you don't need to gather any more metadata, just add a link to the generated text...

**Comment by martinthomson** [comment]
To give an example, some of the drafts in the HTTP repo (or at least one of them anyway) include the following:

```
The most recent (often, unpublished) draft is at <https://httpwg.org/http-extensions/draft-ietf-httpbis-targeted-cache-control.html>.

See also the draft's current status in the IETF datatracker, at
<https://datatracker.ietf.org/doc/draft-ietf-httpbis-targeted-cache-control/>.
```

This is useful information generally, though if this is included, it might be wise to change the title of the generated section to: "About This Draft".

It is fairly easy to generate the first link for a github repository if the naming convention is consistent.  It is "https://#{user}.github.io/#{repo}/#{draftname}.html".  But in the example above, you need to know some additional metadata if you want to provide the correct link.  It might be easier overall to accept a "latest" label.

The datatracker link can be generated from the draft name.

**Comment by cabo** [comment]
Maybe we can trigger the GitHub.io heuristic on the presence of the GitHub key and a setting like

```
venue:
  editor-copy: true
```

**Comment by martinthomson** [comment]
I was thinking that perhaps I could just automate the population of the link.
