### ISSUE TITLE
blockquote

### ISSUE THREAD

**Issue by mnot** [cabo/kramdown-rfc2629#156]
Right now, quoted sections are converted to XML lists. This seems odd to me -- why not `<blockquote>`?

**Comment by cabo** [comment]
Backwards compatibility (there was no <blockquote in v2).

Use

    {:quote}
    > The future is already here, it is just not evenly distributed.

Similar for an aside:

    {:aside}
    > The correct unit for bitrate is bit/s, not bps.

See https://github.com/cabo/kramdown-rfc2629/wiki/Syntax#special-ial-attributes

**Comment by mnot** [comment]
Thanks.
