### ISSUE TITLE
Smart quotes in output

### ISSUE THREAD

**Issue by britram** [cabo/kramdown-rfc2629#16]
kramdown-rfc2629 appears to use kramdown's defaults to smartify quotes, on which current versions of xml2rfc seem to choke. I can't find a reasonable place to inject the usual hack to make kramdown _not_ smartify quotes `("--smart-quotes apos,apos,quot,quot")` into a Make-based toolchain using kramdown-rfc2629. What am I missing here? I presume I'm not the only person who's had this problem but my Google-fu is failing me today.

**Comment by cabo** [comment]
Hi Brian,

xml2rfc actually can cope with kramdown-rfc2629's Unicode input if you don't set coding: ascii in the YAML.  I'm looking at a way to make sure that the coding actually is ASCII when you set that (I received another bug report only a couple of days ago), but it's not been a problem without the coding: ascii so far.

**Comment by britram** [comment]
hi Carsten,

Hm, not setting coding: ascii in the YAML, and xml2rfc is giving me this:

```
xml2rfc draft-ietf-taps-transports.xml -o draft-ietf-taps-transports.txt --text
Parsing file draft-ietf-taps-transports.xml
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/xml2rfc/utils.py", line 283, in safeReplaceUnicode
    element.text = element.text.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 119: ordinal not in range(128)
```

This might be an xml2rfc problem then. I'm hacking a sed workaround into my makefile in the meantime. :/

Cheers, B

**Comment by cabo** [comment]
The RFC editor has decided that RFC XML is ASCII, a couple years after kramdown-rfc2629 became stable.  So maybe XML2RFC has been broken recently.  Can you show me the <?xml line you are working from?

**Comment by britram** [comment]
kramdown-rfc2629 generates:

<?xml version="1.0" encoding="UTF-8"?>

(see https://github.com/britram/taps-transports/ ; it's using Martin Thomson's toolchain, I backed out the .sqxml hack for now)

**Comment by cabo** [comment]
OK, that's what I'm using, too, and I get nice smart quotes in the HTML and nice ASCII quotes in the TXT.  Just checked, I'm using xml2rfc 2.5.0.  What are you using?

**Comment by cabo** [comment]
Whoa.  I'm seeing what you mean by trying to format what's in that repo.
Except that I'm getting a zillion of "WARNING: Illegal character replaced in string: 	"
Ouch, there are tab characters in the input?
If I fix that, there is no problem.

**Comment by cabo** [comment]
One difference might be that you are using python3.4, while I'm using python2.7.
I'll need to add testing for xml2rfc on python3.4...

**Comment by cabo** [comment]
If xml2rfc on python3.4 no longer can handle non-ASCII input, I'll also need to handle dashes and other typographic conversions...

The workaround I'd suggest is actually the other way around: just set `coding: ascii` and make sure your source text indeed is ascii.

**Comment by britram** [comment]
(sorry, got interrupted.)

I've tried this (that's `coding: ascii` at the top-level of the YAML, yes?) and end up with the same result.

I can spend a little time digging into differences of string.encode on 2.7 and 3.7 tomorrow or next week. In the meantime I think I'll fall back to sed.

Many thanks for your help!

Cheers, B

**Comment by cabo** [comment]
Here's the header from one file:

```yaml
---

title: Concise Binary Object Representation (CBOR) Tags for Typed Arrays
abbrev: CBOR tags for typed arrays
docname: draft-jroatch-cbor-tags-00pre
date: 2014-02-09

coding: us-ascii
stand_alone: true
```

The resulting XML does not have anything outside of ASCII for this file or for draft-ietf-taps-transports.md once I have `coding: us-ascii` in there, so I don't know how you get any.
(Anyway, you'll need to get rid of the tab characters in the input to work with xml2rfc on python 2.7.)

**Comment by MikeBishop** [comment]
@martinthomson and I just ran into this trying to take a change to use Python 3.x in the i-d template.  For some reason, while it doesn't choke on my local machine, it's causing issues on Circle.

**Comment by cabo** [comment]
There is a parallel discussion of a potential XML2RFC regression with Python 3 and beyond-ASCII characters in https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/338 -- here there also is a failure on some systems and not on others.

I'll look into this in more detail tomorrow (it's close to midnight here).

**Comment by martinthomson** [comment]
I don't think that this is an issue here.  xml2rfc should handle the smart quotes.  It's possible that @MikeBishop installed xml2rfc using python 2, which would suppress the issue locally.

**Comment by MikeBishop** [comment]
Given that I don't have Python 2.x installed on that system at all, it seems unlikely.

**Comment by jyasskin** [comment]
xml2rfc-2.15.0 stops working with non-ascii input. The release notes at https://pypi.org/project/xml2rfc/2.15.0/ talk about using a `<u>` element to mark unicode, but that's clearly not what we actually want for smart quotes.

**Comment by jyasskin** [comment]
A workaround seems to be to pass `--utf8` to xml2rfc, which can be done in https://github.com/martinthomson/i-d-template/blob/master/config.mk#L7. This produces a deprecation warning, but the build succeeds.

**Comment by mnot** [comment]
Whether or not xml2rfc can handle the smart quotes, the RFC Editor is removing smart quotes in submitted XML, causing a significant and noisy diff for AUTH48. Could kramdown-rfc2629 please either default to disabling them, or allow it in configuration?

**Comment by cabo** [comment]
```
stand_alone: yes
smart_quotes: no
```

are two settings in the YAML header that for one reason or another should be the default now, but aren't for backwards compatibility.

**Comment by mnot** [comment]
Thanks. Maybe add that to docs (or did I miss it?) @martinthomson might also be good to doc in your template...

**Comment by cabo** [comment]
I could change the default for --v3, though.

**Comment by cabo** [comment]
README says:

(1.0.31:)
The kramdown `smart_quotes` feature can be controlled better.
By default, it is on (with default kramdown settings), unless `coding:
us-ascii` is in effect, when it is off by default.
It also can be explicitly set on (`true`) or off (`false`) in the YAML
header, or to a specific value (an array of four kramdown entity names
or character numbers).  E.g., for a German text (that is not intended
to become an Internet-Draft), one might write:

```yaml
smart_quotes: [sbquo, lsquo, bdquo, ldquo]
pi:
  topblock: no
  private: yes
```

**Comment by martinthomson** [comment]
I've updated the template I use with this directive.  Not sure how many people use that as opposed to cloning an existing document though.

**Comment by cabo** [comment]
I changed the default for `--v3` to `smart_quotes: false` (1.3.14).

This does not address dashes etc.

**Comment by cabo** [comment]
https://mailarchive.ietf.org/arch/msg/rfc-markdown/TlY-yCb58mADnQy6KxrD8RNWjFo/
