### ISSUE TITLE
List styles

### ISSUE THREAD

**Issue by mnot** [cabo/kramdown-rfc2629#17]
It would be great if there were some way to pass in alternate list styles for OL, UL and DL; e.g., a command-line option.

See:
  https://www.rfc-editor.org/rfc-editor/xml2rfcFAQ.html#q_fancy_lists

**Comment by cabo** [comment]
Here is an excerpt from the source of the CDDL draft:

```markdown

{: style="format (G%d)"}
* Provide an unambiguous description of the overall structure of a CBOR data structure.

* Flexibility to express the freedoms of choice in the CBOR data format.

* Possibility to restrict format choices where appropriate [^_format].
```

Is that what you mean?
Or do you need a general setting that just applies to every ol/ul/dl?

**Comment by mnot** [comment]
That's what I mean -- THANKS!

One question: How does one do it in a list of lists? E.g.,

1. thing...
2. other thing...
    1. sub-thing
    2. sub-thing returns

I can make it work on the outer list, but putting that on the inner list seems to either not work, or cause errors.

**Comment by mnot** [comment]
Never mind, got it working by putting a blank line above. Thanks!
