### ISSUE TITLE
Feature request: make refcache update optional

### ISSUE THREAD

**Issue by yaronf** [cabo/kramdown-rfc2629#20]
So that the tool can be run off-line, too. Obviously the default behavior should remain as-is.

Thanks!

**Comment by cabo** [comment]
What happens when you run it offline?  It is supposed to "just work" if it cannot reach the Internet...

If kramdown-rfc2629 is maybe blocking on anything, a quick hack you can do is set the environment variable `XML_RESOURCE_ORG_HOST` to, say, `localhost` -- this should ensure you get a fast fail.

**Comment by yaronf** [comment]
You are right, sorry.

```
.refcache/reference.RFC.6962.xml: renewing (stale by 0.1 days)
*** getaddrinfo: Temporary failure in name resolution while fetching https://unicorn-wg.github.io/idrefs/bibxml/reference.RFC.6962.xml
```
