### ISSUE TITLE
Warn on HT characters in input; never emit HT characters in output

### ISSUE THREAD

**Issue by cabo** [cabo/kramdown-rfc2629#24]
XML2RFC sometimes goes into an endless loop when it encounters HT characters.
In any case, it is not clear why they should be in a markdown input document.
In particular in artwork, where HT characters have caused e.g. the RFC 7386/7396 disaster.

**Comment by miekg** [comment]
Really? Wow. Is there an issue to track in the xml2rfc issue tracker?

**Comment by cabo** [comment]
I never got around to creating an isolated test case.  Apparently, nobody cares :-)

**Comment by cabo** [comment]
(This was fixed 9 months ago in 1.0.31 by never emitting HT characters and by issuing a warning if any are encountered in the input.)
