### ISSUE TITLE
should kramdown &-stuff URLs in references?

### ISSUE THREAD

**Issue by mcr** [cabo/kramdown-rfc2629#28]
I just got bit by a URL in my references section that had an & in the URL.  This got passed through to xml2rfc, which mysteriously complained, and finally I found the & had to be &amp;.  Should kramedown-rfc2629 do this stuffing for us?

    <reference anchor="PFS" target="https://en.wikipedia.org/w/index.php?title=ForwardSecrecy&oldid=731318899">

**Comment by cabo** [comment]
Yes, it should.
kramdown-rfc currently is not careful at all in computing attribute values from metadata (it *is* quite careful with attribute values taken from text).
I hope nobody has used this bug for creative purposes...

**Comment by cabo** [comment]
Should be fixed in 1.0.36 (`gem update` to get it)
