### ISSUE TITLE
can't create a *ref to the 'References' section

### ISSUE THREAD

**Issue by phluid61** [cabo/kramdown-rfc2629#31]
I'm trying to comply with the IANA template in [RFC 7595](https://tools.ietf.org/html/rfc7595#section-7.4) by writing something like "`See {{references}} of this document`" but I can't create a *ref to the 'References' section.

This means that I have to count how many section there are and explicitly type out "Section 8", and then update it if my document structure changes.

This may be a deficiency of XML2RFCv2 moreso than kramdown-rfc2629 but feedback or advice would be helpful.

**Comment by cabo** [comment]
Interesting. I don't know how to do this in RFC 7749 RFCXML, so I don't know how to add this to kramdown-rfc.  I'll bring this up on the xml2rfc mailing list.

**Comment by cabo** [comment]
On the rfc-interest mailing list, actually.
https://www.rfc-editor.org/pipermail/rfc-interest/2016-November/009748.html

**Comment by cabo** [comment]
It doesn't seem that this can be addressed.
https://www.rfc-editor.org/pipermail/rfc-interest/2016-November/009749.html
