### ISSUE TITLE
feature request: include files

### ISSUE THREAD

**Issue by mcr** [cabo/kramdown-rfc2629#37]
It would be nice if we could includes files in the mkd and have them pasted into the XML.
This would be useful for including YANG definitions into RFCs.  So in particular being able to style them as code blocks would rock.

**Comment by cabo** [comment]
This is such a great feature request that it was implemented about six years ago :-)

README.md says:

(0.x:) Files can be included with the syntax `{::include fn}` (needs
to be in column 1 since 1.0.22; can be suppressed for use in servers
by setting environment variable KRAMDOWN_SAFE since 1.0.22).  A
typical example from a recent RFC, where the contents of a figure was
machine-generated:

```markdown
~~~~~~~~~~
{::include ../ghc/packets-new/p4.out}
~~~~~~~~~~
{: #example2 title="A longer RPL example"}
```

[That RFC is RFC7400.]

These includes paste in the markdown though; do you really need to paste in XML?

**Comment by mcr** [comment]
cabo <notifications@github.com> wrote:
    > This is such a great feature request that it was implemented about six
    > years ago :-)

    > README.md says:

Damn.  I searched source code for include, but not in the README...

    > (0.x:) Files can be included with the syntax {::include fn} (needs
    > to be in column 1 since 1.0.22; can be suppressed for use in servers
    > by setting environment variable KRAMDOWN_SAFE since 1.0.22). A
    > typical example from a recent RFC, where the contents of a figure was
    > machine-generated:

    > ~~~~~~~~~~
    > {::include ../ghc/packets-new/p4.out}
    > ~~~~~~~~~~
    > {: #example2 title="A longer RPL example"}

    > [That RFC is RFC7400.]

    > These includes paste in the markdown though; do you really need to
    > paste in XML?

Hmm. I'd have to put the ~~~~~~~~ into the other file.
It would be nice to have a codeinclude or something like that...

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by cabo** [comment]
On 26 Feb 2017, at 03:06, Michael Richardson <notifications@github.com> wrote:
> 
> Hmm. I'd have to put the ~~~~~~~~ into the other file.

Please explain.  What is the other file?  Why?

> It would be nice to have a codeinclude or something like that...

The main problem with this is that there are so many parameters one could think of that it is easier just to write the ~~~ (and possibly an attribute list, as in the example) around the include.

Grüße, Carsten

**Comment by mcr** [comment]
cabo <notifications@github.com> wrote:
    > On 26 Feb 2017, at 03:06, Michael Richardson
    > <notifications@github.com> wrote:
    >>
    >> Hmm. I'd have to put the ~~~~~~~~ into the other file.

    > Please explain. What is the other file? Why?

I was thinking that once I wrote made the code block with the ~~~~~~~~~, that
everything in between would be interpreted literally, so I couldn't put the
include in there.

    >> It would be nice to have a codeinclude or something like that...

    > The main problem with this is that there are so many parameters one
    > could think of that it is easier just to write the ~~~ (and possibly
    > an attribute list, as in the example) around the include.

But, how do we write examples that start with {:include ? Is there an escape
for that?

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by cabo** [comment]
On 26 Feb 2017, at 17:33, Michael Richardson <notifications@github.com> wrote:
> 
> cabo <notifications@github.com> wrote:
> > On 26 Feb 2017, at 03:06, Michael Richardson
> > <notifications@github.com> wrote:
> >>
> >> Hmm. I'd have to put the ~~~~~~~~ into the other file.
> 
> > Please explain. What is the other file? Why?
> 
> I was thinking that once I wrote made the code block with the ~~~~~~~~~, that
> everything in between would be interpreted literally, so I couldn't put the
> include in there.

No, as the example shows, the {::include …} is interpreted everywhere in the original input file (no nesting, though).  Actually, this code runs before even the markdown parsing starts.

> But, how do we write examples that start with {:include ? Is there an escape
> for that?

If you care about that example being in column 1, you can't, no.
Is that a problem for you?
(It might be for the upcoming I-D about kramdown-rfc.)

Grüße, Carsten

**Comment by cabo** [comment]
On 26 Feb 2017, at 18:23, Carsten Bormann <cabo@tzi.org> wrote:
> 
> If you care about that example being in column 1, you can't, no.

That is of course true only if you insist on using the ~~~ form.
Workarounds:

(1) include a file with the {::include text in it (includes do not nest)

(2) use indented code blocks as in

```
Include your file fn.md with

    {::include fn.md}
{: #example-with-include}
```

Grüße, Carsten
