### ISSUE TITLE
Feature request: support submissionType and consensus

### ISSUE THREAD

**Issue by fenner** [cabo/kramdown-rfc2629#39]
I'm trying to update a kramdown-written document to match what the RFC Editor has done to it.  I'd like to set the attributes submissionType="IETF" and consensus="yes" in the <rfc> element.

**Comment by cabo** [comment]
1.0.41 now has these additional attributes in <rfc> as top level YAML variables (and provides convenient aliases):

```
+                  "consensus", "submissionType=submissiontype", "xml:lang=lang",
```

Note that "yes" means true in YAML, so you have to quote it:

```
consensus: 'yes'
```
