### ISSUE TITLE
is there a way to comment things out?

### ISSUE THREAD

**Issue by mcr** [cabo/kramdown-rfc2629#41]
Despite: https://stackoverflow.com/questions/4823468/comments-in-markdown
which kinda works, but fails on line 1 for me..
I really just want to be able to leave comments for other people editing, but also to be able to put "-*- markdown -*-" so that emacs will do the right thing even if I haven't configured .mkd to do that.

**Comment by cabo** [comment]
line 1 is not markdown, but yams.  I'm not aware of a way to put a comment in line 1; in all other lines you can use # as the yaml comment character.

For a badly configured Emacs, put this in the last three lines:

```
<!-- Local Variables: -->
<!-- mode: markdown -->
<!-- End: -->
```

(but I'd rather configure Emacs right).

**Comment by cabo** [comment]
So did that solve your problem or do we need some new feature here?
