### ISSUE TITLE
Use of triple backtick does not generate pre style code blocks

### ISSUE THREAD

**Issue by heartsucker** [cabo/kramdown-rfc2629#43]
For example (escaping the backslashes for GH)
```
\`\`\`
test
test
test
\`\`\`
```

renders to

```xml
<t><spanx style="verb">test
test
test</spanx></t>
```

Which when run through `xml2rfc` does not give `pre` style code blocks. I'm not sure if this is a limitation of `kramdown` or `xml2rfc` itself, but this seemed like the place to report it.

**Comment by cabo** [comment]
The triple backtick isn't markdown syntax (even though github flavored markdown has made it quite popular).  Kramdown does support the usual tilde-based version:

```
~~~ abnf
foo = bar
bar = baz
~~~
```

as well as the indented version of a code block.

Do you think we need to support the GFM style as well?

**Comment by heartsucker** [comment]
Ah, this was totally my misunderstanding. Thank you!

**Comment by heartsucker** [comment]
And I guess it would be nice if it supported GFM, but so long as I can get it to render how I need, I don't much care.

**Comment by cabo** [comment]
Right.  The reason I don't just want to drop it in is that ````` ``` ... ``` ````` already has a meaning as a code span (within a paragraph) that might include backquotes, so supporting GFM type here might break existing source files.
