### ISSUE TITLE
Unnumbered sections after the appendixes

### ISSUE THREAD

**Issue by emanjon** [cabo/kramdown-rfc2629#47]
RFCs always have unnumbered headings after the Appendixes. Normally "Acknowledgments" and "Authors' Addresses", but other sections such as "Contributors" and "IAB Members at the Time of Approval" are common. These sections are listed in the ToC.

While kramdown-rfc2629 takes care of Authors' Addresses, I do not find how to create other such headings like "Acknowledgments". Is there a need for more sections than abstract, middle, back, and fluff? Or am I just missing how to do this?

RFC Examples:

RCFC8212

   1.  Introduction  . . . . . . . . . . . . . . . . . . . . . . . .   2
   2.  Terminology . . . . . . . . . . . . . . . . . . . . . . . . .   3
     2.1.  Requirements Language . . . . . . . . . . . . . . . . . .   3
   3.  Changes to RFC 4271 . . . . . . . . . . . . . . . . . . . . .   3
   4.  Security Considerations . . . . . . . . . . . . . . . . . . .   4
   5.  IANA Considerations . . . . . . . . . . . . . . . . . . . . .   4
   6.  References  . . . . . . . . . . . . . . . . . . . . . . . . .   4
     6.1.  Normative References  . . . . . . . . . . . . . . . . . .   4
     6.2.  Informative References  . . . . . . . . . . . . . . . . .   5
   Appendix A.  Transition Considerations for BGP Implementers . . .   6
     A.1.  "N+1 N+2" Release Strategy  . . . . . . . . . . . . . . .   6
   Acknowledgments . . . . . . . . . . . . . . . . . . . . . . . . .   6
   Contributors  . . . . . . . . . . . . . . . . . . . . . . . . . .   7
   Authors' Addresses  . . . . . . . . . . . . . . . . . . . . . . .   7

RCFC8170

   1.  Introduction  . . . . . . . . . . . . . . . . . . . . . . . .   2
   2.  Extensibility . . . . . . . . . . . . . . . . . . . . . . . .   4
   3.  Transition vs. Coexistence  . . . . . . . . . . . . . . . . .   5
   4.  Translation/Adaptation Location . . . . . . . . . . . . . . .   6
   5.  Transition Plans  . . . . . . . . . . . . . . . . . . . . . .   7
     5.1.  Understanding of Existing Deployment  . . . . . . . . . .   7
     5.2.  Explanation of Incentives . . . . . . . . . . . . . . . .   7
     5.3.  Description of Phases and Proposed Criteria . . . . . . .   8
     5.4.  Measurement of Success  . . . . . . . . . . . . . . . . .   8
     5.5.  Contingency Planning  . . . . . . . . . . . . . . . . . .   8
     5.6.  Communicating the Plan  . . . . . . . . . . . . . . . . .   9
   6.  Security Considerations . . . . . . . . . . . . . . . . . . .   9
   7.  IANA Considerations . . . . . . . . . . . . . . . . . . . . .   9
   8.  Conclusion  . . . . . . . . . . . . . . . . . . . . . . . . .  10
   9.  Informative References  . . . . . . . . . . . . . . . . . . .  10
   Appendix A.  Case Studies . . . . . . . . . . . . . . . . . . . .  14
     A.1.  Explicit Congestion Notification  . . . . . . . . . . . .  14
     A.2.  Internationalized Domain Names  . . . . . . . . . . . . .  15
     A.3.  IPv6  . . . . . . . . . . . . . . . . . . . . . . . . . .  17
     A.4.  HTTP  . . . . . . . . . . . . . . . . . . . . . . . . . .  19
       A.4.1.  Protocol Versioning, Extensions, and 'Grease' . . . .  20
       A.4.2.  Limits on Changes in Major Versions . . . . . . . . .  20
       A.4.3.  Planning for Replacement  . . . . . . . . . . . . . .  21
   IAB Members at the Time of Approval . . . . . . . . . . . . . . .  22
   Acknowledgements  . . . . . . . . . . . . . . . . . . . . . . . .  22
   Author's Address  . . . . . . . . . . . . . . . . . . . . . . . .  22

**Comment by cabo** [comment]
Sorry, I missed this issue (and some 20 more :-/).

For a while now, the clumsy way to do this is to directly access the XML attribute, as in:

```
Acknowledgements
================
{: numbered="no"}

John Mattsson was nice enough to point this out.
```
