### ISSUE TITLE
Certificate check should also look for OpenSSL::X509::DEFAULT_CERT_DIR

### ISSUE THREAD

**Issue by jyasskin** [cabo/kramdown-rfc2629#48]
Checking for just `OpenSSL::X509::DEFAULT_CERT_FILE` leaves out folks using the [debian openssl package](https://packages.debian.org/buster/amd64/openssl/filelist), which creates a `/usr/lib/ssl/certs` directory instead of a `/usr/lib/ssl/cert.pem`.

**Comment by cabo** [comment]
Right, that heuristic is rather shoddy; fortunately, a false negative isn't too much of a disaster as the certs in the `certified` gem so far generally do work.  

The problem with looking at the existence of `OpenSSL::X509::DEFAULT_CERT_DIR` is that we don't know if there is anything useful in there.  Maybe we should try to open a TLS connection to xml2rfc.tools.ietf.org and apply the workaround if that fails with a cert verification failure.  ("Apply less secure fall back when I might be under attack" isn't such a great security strategy though.  A heuristic that would be able to decide without taking input from a security failure would be preferable.)

**Comment by cabo** [comment]
Covered by my cover-up for #50.
(Please check in your environment.)

**Comment by jyasskin** [comment]
I no longer get the error. Thanks!
