### ISSUE TITLE
conflicts between references and sections

### ISSUE THREAD

**Issue by mcr** [cabo/kramdown-rfc2629#52]
Given a section named:

`# Pledge
`
and a reference:

```
  pledge:
    title: "Dictionary.com Unabridged"
    target: "http://dictionary.reference.com/browse/pledge"

```

They conflict by creating anchor="pledge" for both.  I suggest that maybe generated anchor for section be prefixed with "section-" or something like that.

**Comment by cabo** [comment]
Yeah, similar things happen if you have two sections of the same name.

Unfortunately, it is too late to change the algorithm for generating anchors: that would invalidate all the documents that use them.

So you'll have to manually add a different anchor to your "Pledge" section.

**Comment by cabo** [comment]
Well, maybe that change could be opt-in, via the YAML metadata; something like `section-anchor-prefix` or so.

**Comment by cabo** [comment]
Oh, that idea is so great that it already is implemented (via kramdown `{::options...}`):

https://kramdown.gettalong.org/options.html

So, right after

```
--- middle
```

just say

```
{::options auto_id_prefix="sec-" /}
```

**Comment by cabo** [comment]
1.2.9 will let you do the same from the YAML:

```
kramdown_options:
  auto_id_prefix: sec-
```
