### ISSUE TITLE
reference bibxml URL directly

### ISSUE THREAD

**Issue by mcr** [cabo/kramdown-rfc2629#56]
I have created some bibxml format files that do not (yet?) live on xml2rfc.tools.ietf.org.
I think that xml2rfc would be happy if I could pass a <!ENTITY foobar... > entry through to it.
Is there a way to just put the URL that I want to point to into the normative:/informative: sections of the YAML?

**Comment by mcr** [comment]
cabo <notifications@github.com> wrote:
    > I think I tried to avoid randomly dereferencing URIs, which becomes a
    > security issue (but then there is {::include}).  This could be added
    > after I return from vacation. Care to flesh out the idea a bit?

Could be that I just set some $VARIABLES or cmdline arguments of places
to look in addition to xml2rfc.tools.ietf.org.  Could include file://
URLs.

Basically, I just wrote:
        http://www.sandelman.ca/SSW/ietf/bibxml/

because I needed it, but now I'm not sure how to reference it nicely.
I guess if the XML is gonna be processed by others, one needs to the
entire URL.

I don't know how to use ::include to create <ENTITY things in the heading.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by cabo** [comment]
For now, it is certainly easier to put the content of that XML file into yaml form into the yaml header. {::Include} would work there. 

Kramdown-rfc does not use entities unless you set standalone to false. Why would you want to use them?  To get xml2rfc to do the dereferencing? Easier to {::include} the XML in the references section (but I forget how to do this exactly). Much easier to forget XML and use yaml.

**Comment by cabo** [comment]
http://www.sandelman.ca/SSW/ietf/bibxml/_reference.ISO.18004.2015.xml has a syntax error that makes it invalid XML.  Also, this reference is indeed easy to put into the YAML.  Can we close this issue?

**Comment by cabo** [comment]
Thanks!
(And thanks for the great "target=" in that bibxml :-)
