### ISSUE TITLE
rfc2629.xslt xml stylesheet reference?

### ISSUE THREAD

**Issue by pusateri** [cabo/kramdown-rfc2629#58]
In a generated version of the XML file, the following stylesheet reference is included at the top:
```
<?xml-stylesheet type="text/xsl" href="rfc2629.xslt" ?>
  <!-- generated by https://github.com/cabo/kramdown-rfc2629 version 1.2.9 -->
```

This was submitted for publication and the result is found here:
[https://tools.ietf.org/id/draft-pusateri-dnssd-update-proxy-00.xml](https://tools.ietf.org/id/draft-pusateri-dnssd-update-proxy-00.xml)

Which when viewed in a browser, is broken because it doesn't know where to find rfc2629.xslt but even if the file was local, the XML file can't be displayed in a modern browser due to unsafe load rules:
```
Unsafe attempt to load URL file:///Users/pusateri/doc/draft-ietf-dnssd-update-proxy/rfc2629.xslt from origin null. Domains, protocols and ports must match.
draft-ietf-dnssd-update-proxy.xml:2
```

So should an online version be included here?

Or should the xml-stylesheet be removed from the XML?

**Comment by cabo** [comment]
I put in that feature about seven years ago.  I think I know why the rules in the browsers changed, but I have no idea why they ended up the way they are now and particularly how different they are between browsers.

For me, this feature still works in Firefox when the files are local, so I use that to look at XML files.
The online link you gave also works in Safari, but with some breakage (it doesn't know as much XSLT as Julian's XSLT presumes).  You also used stand_alone: no (which for historical reasons is still the default), so the references don't work.

My recommendations summarized:

* use stand_alone: true in the YAML header
* use Firefox to look at the generated XML
* use the most recent versions of rfc2629.xslt rfc2629-other.ent rfc2629-xhtml.ent rfc2629.dtd, placed in the same directory where the .xml is.

**Comment by pusateri** [comment]
Thanks. Just verified this works ok with stand_aone: true using Firefox. Where do I find the most recent versions of `rfc2629.xslt rfc2629-other.ent rfc2629-xhtml.ent rfc2629.dtd`? It isn't obvious looking at  search results.

**Comment by pusateri** [comment]
And why not reference stable online versions with href instead of a local version?

**Comment by cabo** [comment]
> And why not reference stable online versions with href instead of a local version?

Can I make that work?  I don't think so.

**Comment by cabo** [comment]
> [...] Where do I find the most recent versions of `rfc2629.xslt rfc2629-other.ent rfc2629-xhtml.ent rfc2629.dtd`? It isn't obvious looking at search results.

I think I'll delegate this question to Julian @reschke — he should know.

**Comment by pusateri** [comment]
> > And why not reference stable online versions with href instead of a local version?
> 
> Can I make that work? I don't think so.

Wouldn't it make the version work at: 
[https://tools.ietf.org/id/draft-pusateri-dnssd-update-proxy-00.xml](
https://tools.ietf.org/id/draft-pusateri-dnssd-update-proxy-00.xml)

**Comment by cabo** [comment]
That already works.  Maybe I don't follow.

**Comment by pusateri** [comment]
> That already works. Maybe I don't follow.

No, you're right. I was confused by an earlier discussion with Henrik. Thanks!

**Comment by cabo** [comment]
The reason the references don't work is that the browser refuses to load them:

```
[Error] Unsafe attempt to load URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2136.xml from origin https://tools.ietf.org. Domains, protocols and ports must match. (draft-pusateri-dnssd-update-proxy-00.xml, line 2, x2)
```

`stand_alone: yes` solves this by resolving these references at XML generation time (which is also needed if you want to modify anchors).  Obvious, Henrik @levkowetz cut put them up on tools.ietf.org as well and you could reference them from there using `XML_RESOURCE_ORG_HOST=tools.ietf.org` and continue to use `stand_alone: no`.  But that won't work on datatracker, etc.

**Comment by pusateri** [comment]
Thanks. I'm happy with stand_alone: yes
I was not aware of that switch.

**Comment by pusateri** [comment]
And it does seem like a better default.

**Comment by reschke** [comment]
The latest release is always in <http://greenbytes.de/tech/webdav/rfc2629xslt.zip>, as explained in <https://greenbytes.de/tech/webdav/rfc2629xslt/rfc2629xslt.html>.

**Comment by reschke** [comment]
bq. The online link you gave also works in Safari, but with some breakage (it doesn't know as much XSLT as Julian's XSLT presumes).

I don't have a Safari to test with. If you tell me what happens, I might be able to fix it. It definitively worked a few years ago.

**Comment by cabo** [comment]
The XSLT errors seem to center around the date calculation:

<img width="1542" alt="image" src="https://user-images.githubusercontent.com/23118/53316952-08945980-38ca-11e9-880f-8fad264f4617.png">

**Comment by cabo** [comment]
(The same page works in Firefox.)

In Safari, the console unfortunately only has error messages about the literature references (separate problem, see above), nothing about the date processing.

**Comment by reschke** [comment]
Now I recall, this is a known issue. See <https://greenbytes.de/tech/webdav/rfc2629xslt/rfc2629xslt.html#xslt.engines.browser> and <https://bugs.webkit.org/show_bug.cgi?id=4079>. The issue might go away when a concrete date is given so that the XSLT doesn't have to ask the OS.

**Comment by cabo** [comment]
Thanks -- I have added myself to the Webkit bug (and probably everybody else interested in this should, too).

**Comment by cabo** [comment]
So the status about the XML display in browsers is:

* Firefox 65 fully works via http:// and via file:///
* Safari 12, Chrome 73, Opera 58 work via http://, but with limited date processing

Bibxml references only work if included via `stand_alone: true` in the YAML header.

Prerequisite is that the four files `rfc2629.xslt rfc2629-other.ent rfc2629-xhtml.ent rfc2629.dtd` are in the same directory as the XML files.  This is the case on http://tools.ietf.org/id — thanks to Henrik Levkowetz — so XML files in the Internet-Draft directory can be viewed right there in the above browsers.  Fresh versions of these files (e.g., for local use) can be obtained from 
http://greenbytes.de/tech/webdav/rfc2629xslt.zip thanks to Julian Reschke.

Thanks to Tom Pusateri for causing this little status refresh.  I'm closing the ticket now.

**Comment by pusateri** [comment]
FYI, on macOS, where only Firefox seems to work to display .xml files correctly, the XML file type is not associated with the Firefox Application and so you have to choose "Show All Applications" and then select Firefox to open the XML file from the Finder.

**Comment by reschke** [comment]
Chromium browsers should be fine as well wrt date processing.
