### ISSUE TITLE
Question on tables

### ISSUE THREAD

**Issue by jam01** [cabo/kramdown-rfc2629#59]
More of a question than a bug. I wrote a few tables with markdown and am using Martin Thompson's I-D template to generate html previews. In the html previews the tables have a nice looking style. However when I generated the xml and uploaded to ietf the tables were just ascii tables even in their html version. 

Is this a known thing, am I missing some attributes or something like that? Or are tables with styles not supported by the ietf versions?

**Comment by cabo** [comment]
Hi Jose,

basic markdown tables (PHP markdown extra style) are supported by kramdown.  kramdown-rfc2629 has a few limitations because RFCXML v2 does not support full generality in headers.

I think what you are describing is the current publishing process for RFCs, which centers around plain text.  RFCs can have a PDF complement, but usually don't.  So when we look at "HTML" for an RFC or I-D, that is generated from the plain text format!

But maybe I don't understand your question -- please provide an example.

**Comment by jam01** [comment]
This is how the table looks on my html preview, hosted here https://phtal-org.github.io/internet-draft-phtal/draft-montoya-phtal.html

![image](https://user-images.githubusercontent.com/10093076/53423791-a0b44080-39a7-11e9-920c-50bd802b28db.png)

and this is what the ietf version looks like

![image](https://user-images.githubusercontent.com/10093076/53423885-d1947580-39a7-11e9-8ff9-168294f0f0e5.png)


Which is not the end of the world. The tooling has definitely been of great help, it was just very confusing to see this result. May have to reconsider using tables in general.

**Comment by jam01** [comment]
Also things like bold emphasis didn't work out well
![image](https://user-images.githubusercontent.com/10093076/53424098-2df79500-39a8-11e9-93a2-1dcffdcd6b58.png)

ietf html version
![image](https://user-images.githubusercontent.com/10093076/53424128-3d76de00-39a8-11e9-80fc-557c96121d73.png)

**Comment by cabo** [comment]
Yes, you are experiencing the limits of the plain-text-centric RFCXMLv2 process.  This will be replaced by the new v3 process soon, which centers around the XML and not the plain TXT.  But for now, what you are seeing is exactly what you should see.

**Comment by jam01** [comment]
Understood! Thanks for the clarification, and for the tool itself.

**Comment by cabo** [comment]
If you upload the XML with the TXT, you can use Firefox (or, with limitations, one of the Webkit browsers) to look at the XML.  As in https://tools.ietf.org/id/draft-pusateri-dnssd-update-proxy-00.xml

**Comment by jam01** [comment]
Oh that is nicer, thanks! Do you have any links about RFCXMLv3? I'd like to know if it's in the near future or not.

**Comment by cabo** [comment]
Oh, you did!  https://tools.ietf.org/id/draft-montoya-phtal-00.xml

RFCXMLv3 is defined in RFC7991. There is a whole slew of RFCs around that.

**Comment by jam01** [comment]
Yeah I suppose I should drive the draft by the text versions instead of the HTML preview, at least for now. Also will have to read up on this new format and what that means for me.
