### ISSUE TITLE
Feature request: Support for "artset"

### ISSUE THREAD

**Issue by yaronf** [cabo/kramdown-rfc2629#67]
Our latest draft includes the following snippet:

```XML
<t>
  <figure anchor="fig-endtoend" title="End to end STAR delegation flow">
    <artset>
      <artwork type="ascii-art" src="art/e2e-flow.ascii-art" />
      <artwork type="svg" src="art/e2e-flow.svg" />
    </artset>
  </figure>
</t>
```

Meaning two versions of the diagram, one for inclusion in the text version of the draft, and one for HTML. It would be nice if we had native support in Kramdown-RFC. Thanks!

**Comment by thomas-fossati** [comment]
This is working now, and documented in https://www.ietf.org/id/draft-fossati-svg-test-02.html

Thanks Carsten!

**Comment by cabo** [comment]
I’ve had this feature request for almost a year now…
Thanks for providing the example data to get this going!

**Comment by cabo** [comment]
1.3.3: kdrfc now has a -p/—-prep flag that generates prepped XML alongside the other outputs

So a typical thing you might do now is:

~~~
  kdrfc -ph3 foo.md
  open foo.html
  (Submit the foo.prepped.xml only.)
~~~
