### ISSUE TITLE
removeInRFC for note sections

### ISSUE THREAD

**Issue by martinthomson** [cabo/kramdown-rfc2629#71]
https://tools.ietf.org/html/rfc7991#section-2.33.1 describes removeInRFC as having a default of "false", which is fine.  I would like to create a `<note>` with a `removeInRFC` attribute set to "true".  How would I do that?

I am cargo-culting the form and adding an IAL doesn't work in either of the following:

```
--- note_Note_to_Readers
{: removeInRFC="true"}
```

This attaches the attribute to the first `<t>` element of the document.  xml2rfc chokes on this.

```
--- note_Note_to_Readers{: removeInRFC="true"}
```

This turns the section heading into a `<t>` element that is part of the abstract.  I think that it might be in a list.  kramdown warns about an IAL being attached to text in this case.  I think that this is failing to match `RE_SECTION` as a result of the whitespace.

**Comment by cabo** [comment]
The processing works by cutting up the markdown into sections and then rearranging it again.
Maybe the cutting up could be done in a more intelligent way, so there is a way to place an IAL.
Thinking about that.

**Comment by cabo** [comment]
The `<note` tag is generated from the ERB as a "HTML" (XML) element.  So any other attributes would have to go there as well.
The way the "title" attribute (<name> in V3) is computed right now is a gross hack anyway; thinking about an upward compatible way now to keep the overall syntax in place.  Something like

```
--- note_About_this_document
```
vs.

```
--- to_be_removed_note_About_this_document
```
Hmm.  About as ugly as it already was.

**Comment by cabo** [comment]
May brain failed to come up with a better alternative to `to_be_removed_note` -- will implement this now.
