### ISSUE TITLE
Bump required kramdown version to 2.x

### ISSUE THREAD

**Issue by Flowdalic** [cabo/kramdown-rfc2629#73]
kramdown 1.17.0, which is currently required by kramdown-rfc2629, has known security issues. This causes, for example, [Gentoo, to remove the kramdown 1.17.0 package](https://github.com/gentoo/gentoo/commit/937a54f6d4125d3a41356a477b8d05138cd50777).

Please consider bumping the required kramdown version to 2.x.

**Comment by cabo** [comment]
Please see https://github.com/gettalong/kramdown/issues/660#issuecomment-670919619

**Comment by cabo** [comment]
So I already "considered" making the jump, but this causes a small matter of programming.

The "security issue" is relevant only if the tool is fed with markdown source from uncontrolled sources, which is not the typical use case (but does merit fixing in conjunction with KRAMDOWN_SAFE).

**Comment by omasanori** [comment]
Does https://github.com/cabo/kramdown-rfc2629/commit/be9407b93654c410dcd158d833d5cf9ead95c3cb fix this issue?

**Comment by cabo** [comment]
Indeed it does!  Thank you for pointing this out.
