### ISSUE TITLE
Definition lists don't create a <dt /><dd /><dd /> sequence

### ISSUE THREAD

**Issue by chrysn** [cabo/kramdown-rfc2629#74]
I can't get kramdown-rfc2629 to produce definition lists with multiple items.

In original kramdown, it works fine (without and with contained paragraphs)

<details><summary>markdown input</summary>

`test.md`

```
one
: uno
which is spanish
: eins
which is german

two

: dos

: zwei
```
</details>

<details><summary>HTML output</summary>

`test.html`

```html
<dl>
  <dt>one</dt>
  <dd>uno
which is spanish</dd>
  <dd>eins
which is german</dd>
  <dt>two</dt>
  <dd>
    <p>dos</p>
  </dd>
  <dd>
    <p>zwei</p>
  </dd>
</dl>
```
</details>

But with kramdown-rfc2629, this inserts intermediate `<dt></dt>` parts (breaking up the semantics), and gives two empty lines in the txt output:

<details><summary>HTML and plain text output as produced by i-d-template via kramdown-rfc2829</summary>

`test.html` part

```html
        <dt>one</dt>
        <dd>
  uno
which is spanish</dd>
        <dt/>
        <dd>eins
which is german</dd>
        <dt>two</dt>
        <dd>
  dos</dd>
        <dt/>
        <dd>zwei</dd>
```

`test.txt` part

```plain
   one
      uno which is spanish

  
      eins which is german

   two
      dos

  
      zwei
```
</details>

I've played around a bit but did not find a way to make the text output have a newline only without doing damage to the HTML layout. For example, replacing the second item's colon with a `<br><br>` gives the desired single-empty-line text output, the HTML output is spaced way too widely (surprise -- that's what I ordered, cranking the typewriter's line feed twice).

What's the right way to produce `<dt>one</dt><dd>uno</dd><dd>eins</dd>` in HTML and a single new line between text output definitions? Does this need adaption in kramdown-rfc2629, or can it be worked around by adjusting the input?

**Comment by cabo** [comment]
The problem is this snippet of Relax-NG:

```
   dl =
     element dl {
[...]
       (dt, dd)+
```

RFCXMLv3 simply does not allow kramdown-rfc to do its job.
Instead, there is the workaround with inserting empty <dt></dt>
We could invent a different workaround.

**Comment by cabo** [comment]
No such different workaround came to mind so far.
I believe we need to litigate the simplistic content model for `dl` in the rfc-interest mailing list; once that is changed, we can reopen this.
