### ISSUE TITLE
Change bibxml to a location that is updated more quickly

### ISSUE THREAD

**Issue by paulehoffman** [cabo/kramdown-rfc2629#75]
https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/ is only updated once a day, while https://datatracker.ietf.org/doc/bibxml3/ is updated almost immediately after submission. This is important for athors who are publishing two new drafts, one of which needs to link to the other.

**Comment by martinthomson** [comment]
This appears to be done already from what I'm seeing in the code.

**Comment by cabo** [comment]
Indeed.  Closed by f046006 (1.3.30).
