### ISSUE TITLE
v3 section titles

### ISSUE THREAD

**Issue by mnot** [cabo/kramdown-rfc2629#76]
... should use `<name>`, not `title=`.

**Comment by cabo** [comment]
Any reason to prioritize this among all the other v3isms?

**Comment by mnot** [comment]
Not particularly, except that it causes diff noise in AUTH48.

It's just an issue on a list of issues :)

**Comment by cabo** [comment]
Fixed in c3ffdd1 (get 1.3.20), along with the capability to have sub/superscripts in section titles.
