### ISSUE TITLE
Dashes

### ISSUE THREAD

**Issue by mnot** [cabo/kramdown-rfc2629#78]
Currently the string `--` in source is converted into an em dash. The RFC Editor converts it back into `--`, so this is unnecessary diff in AUTH48.

I believe [kramdown gives some control of this](https://kramdown.gettalong.org/rdoc/Kramdown/Options.html).

**Comment by cabo** [comment]
Actually, `--` is an en dash; `---` would be an em-dash.
I'm not giving up on the hope that RFCs can get basic typography right sometime this decade.
But, like smart-quotes, there indeed can be an option.

This is a continuation of
https://github.com/cabo/kramdown-rfc2629/issues/16
and I plan to handle this in the same way.

**Comment by mnot** [comment]
Oh, I share your hope; it's just that I'm battling unintended changes in RFCs due to the impenetrability of their diffs...

**Comment by cabo** [comment]
https://mailarchive.ietf.org/arch/msg/rfc-markdown/TlY-yCb58mADnQy6KxrD8RNWjFo/

**Comment by mnot** [comment]
Works for me (in v3) - thank you so much for the amazing turnaround!
