### ISSUE TITLE
ZIP code with leading zero is parsed as octal

### ISSUE THREAD

**Issue by larseggert** [cabo/kramdown-rfc2629#83]
My ZIP code in Markdown is `code: 02700`, which gets converted to `<code>1472</code>` in XML. It should of course be `          <code>02700</code>`.

**Comment by larseggert** [comment]
`code: "02700"` fixes this, but was somewhat non-obvious.

**Comment by cabo** [comment]
Given the way we are using YAML, this is unfixable.
This is instead now addressed in the documentation, specifically in commit 20c623a of the Wiki page about the syntax, https://github.com/cabo/kramdown-rfc2629/wiki/Syntax#pitfalls-in-yaml
