### ISSUE TITLE
Superfluous angle brackets

### ISSUE THREAD

**Issue by larseggert** [cabo/kramdown-rfc2629#85]
Even when a URL is already enclosed in angle brackets, kramdown-rfc2629 adds another pair.

Source
```
target: <https://pfld.net/2006/paper/s2_03.pdf>
```
becomes
```
target="&lt;https://pfld.net/2006/paper/s2_03.pdf&gt;"
```

**Comment by cabo** [comment]
Doctor, it hurts when...

I'd say "works as designed".  

This is for bibliography entries?  I can add some code to unwrap URIs, if needed.

**Comment by larseggert** [comment]
Markdownlint complains for bare URLs, which is why I added the brackets...

**Comment by cabo** [comment]
But this is in the YAML, no?
Markdownlint has no business complaining about the YAML, I'd say.

**Comment by cabo** [comment]
Hack:

(1) use this as the last line of the YAML:

```
stand_alone: ---
```

(2) use `mdl -i`

There is still one spurious "MD034 Bare URL used" for the end-of-YAML marked introduced in (1); no idea what is wrong about that.
