### ISSUE TITLE
rubygems has 1.3.24, this repo has only 1.3.23

### ISSUE THREAD

**Issue by dkg** [cabo/kramdown-rfc2629#91]
https://rubygems.org/gems/kramdown-rfc2629 shows 1.3.24 as the latest version, but the `master` branch here  is at 911495f5b3db820aa2e090e3ba0e5e6227de8914, which is only 1.3.23

maybe 1.3.24 hasn't been pushed?

**Comment by cabo** [comment]
Fixed.  Sorry about that, and thanks for the reminder.
