### ISSUE TITLE
Link to 3rd-part tools

### ISSUE THREAD

**Issue by larseggert** [cabo/kramdown-rfc2629#97]
`README` currently says:
>Currently supported labels as of 1.3.9:
>
>goat, ditaa: ASCII (plaintext) art to figure conversion
mscgen: Message Sequence Charts
plantuml: widely used multi-purpose diagram generator
plantuml-utxt: Like plantuml, except that a plantuml-generated plaintext form is used
mermaid: Very experimental; the conversion to SVG is prone to generate black-on-black text in this version

Could you add links to these tools? Googling "goat svg" or "mermaid svg" is not exactly returning useful hits.

Also, "math" is missing from the list.

**Comment by larseggert** [comment]
`ditaa` seems to be https://github.com/stathissideris/ditaa now

**Comment by cabo** [comment]
Thanks! Fixed.
